language: C
compiler: gcc
dist: trusty
sudo: required

install:
  - sudo apt-get install pkg-config libtool autoconf automake cmake bash
  - git clone https://github.com/akheron/jansson
  - cd jansson && autoreconf -i && ./configure && make && sudo make install && cd ..
  - git clone https://github.com/edenhill/librdkafka
  - cd librdkafka && ./configure && make && sudo make install && cd ..
  - git clone https://github.com/alanxz/rabbitmq-c
  - cd rabbitmq-c && mkdir build && cd build && cmake .. && sudo cmake --build . --target install && cd .. && cd ..
  - git clone --recursive https://github.com/maxmind/libmaxminddb 
  - cd libmaxminddb && ./bootstrap && ./configure && make && sudo make install && cd ..
  - git clone -b 2.0-stable https://github.com/ntop/nDPI
  - cd nDPI && ./autogen.sh && ./configure && make && sudo make install && cd ..
  - git clone https://github.com/zeromq/libzmq.git
  - cd libzmq && ./autogen.sh && ./configure && make && sudo make install && cd ..

script:
  - ./autogen.sh
  - ./configure --enable-mysql --enable-pgsql --enable-sqlite3 --enable-kafka --enable-geoipv2 --enable-jansson --enable-rabbitmq --enable-nflog --enable-ndpi --enable-zmq
  - make
  - sudo make install
  - make distcheck

addons:
  apt:
    packages:
      - libpcap-dev
      - libpq-dev
      - libsqlite3-dev
      - libmysqlclient-dev
      - libnetfilter-log-dev
      - mysql-client-5.6
      - libtool
      - autoconf
      - automake
